src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('testify/', include('testify.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

src/accounts/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.DecimalField(default=0.0, decimal_places=2, max_digits=5,
                                validators=[MinValueValidator(0), MaxValueValidator(100)])
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from accounts.models import User


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username']


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'bio',
            'birth_date',
            'image'
        ]

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from accounts.forms import AccountCreateForm, AccountUpdateForm
from accounts.models import User


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.info(self.request, f"New user has just been created!")
        return result


class AccountLoginView(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('core:index')

    def form_valid(self, form):
        result  = super().form_valid(form)
        messages.info(self.request, f'User {self.request.user} has been successfully logged in!')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def get(self, request, *args, **kwargs):
        result = super().get(request, *args, **kwargs)
        messages.info(self.request, f'User {self.request.user} has been logged out!')
        return result


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('core:index')

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordUpdateView(LoginRequiredMixin, PasswordChangeView):
    model = User
    template_name = 'password.html'
    success_url = reverse_lazy('accounts:login')

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Log in as a user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Log in">
            <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>User is logged out</h1>
{% endblock %}

{% block content %}
        <a class="btn btn-light" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Edit user</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">

        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.image.url }}">
            </div>
    {#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
    {#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>


        {% csrf_token %}

        {{form|crispy}}
{#        <div class = 'mb-3'>#}
{#            Raw passwords are not stored, you can change the password <a href="{% url 'accounts:password' %}">this form</a>#}
{#        </div>#}
{#        {{profile_form|crispy}}#}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Register new user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Register">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>
    </form>
{% endblock %}