src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('testify/', include('testify.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}
        <title>Testify</title>
{% endblock %}
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">
  <div class="container">

  <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Tests<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:index' %}">Leaderboard</a>
      </li>
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#      </li>#}
    </ul>

    <ul class="navbar-nav ">

            {%  if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                  </li>
            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
            {% endif %}

    </ul>

  </div>
  </div>
</nav>

  <div class="container">
{#            {% block header %}#}
{#                <h1>#}
{#                Welcome to LMS!#}
{#                </h1>#}
{#            {% endblock%}#}
{##}

            {% include 'includes/messages.html' %}

            <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
                {% block header %}
                    <h1>
                        Welcome to Testify!!!
                    </h1>
                {% endblock %}
            </div>



            {% block content %}
            {% endblock %}
  </div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}